services:
  keycloak_admin_console:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:20.0.0
    # image: quay.io/keycloak/keycloak:26.5.5
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_ADMIN_URL: https://localhost:8443
      KC_HOSTNAME_URL: https://localhost:8443
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - keycloak_nginx_dev_network

  postgres_keycloak:
    container_name: postgres_kc_container
    # image: postgres:14.2
    image: postgres:15-alpine
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_nginx:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      # test: "exit 0"
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    networks:
      - keycloak_nginx_dev_network

  nginx_keycloak:
    container_name: nginx_kc_container
    build:
      context: .
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - keycloak_admin_console
    networks:
      - keycloak_nginx_dev_network

volumes:
  pgdata_keycloak_nginx:

networks:
  keycloak_nginx_dev_network:
    driver: bridge